---

services:
  db:
    image: postgres:17-bookworm
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - type: bind
        source: ${PWD}/
        target: /app/
    ports:
      - 5432:5432
  tool:
    build: .
    working_dir: /app/
    volumes:
      - type: bind
        source: ${PWD}/
        target: /app/
  evidence:
    build: ./my-evidence/
    volumes:
      - type: bind
        source: ${PWD}/my-evidence/
        target: /app/
    ports:
      - 3000:3000
