commands:
    git-shallow-clone:
        description: git shallow clone
        steps:
            - run:
                command: |
                    #!/usr/bin/env sh
                    set -eu
                    # プロジェクトの値と変数
                    # https://circleci.com/docs/ja/variables/
                    echo "現在ビルド中のブランチ名: ${CIRCLE_BRANCH}"
                    echo "リポジトリURL: ${CIRCLE_REPOSITORY_URL}"
                    echo "コミットのSHA1ハッシュ: ${CIRCLE_SHA1}"
                    echo "pwd: ${PWD}"
                name: 変数表示(デバッグ用)
            - run:
                command: |
                    #!/usr/bin/env sh
                    set -eu
                    #set -x
                    # -e: エラーが発生した時点でスクリプトを終了
                    # -u: 未定義の変数を使用した場合にエラーを発生
                    # -x: スクリプトの実行内容を表示(debugで利用)

                    export SSH_CONFIG_DIR="${SSH_CONFIG_DIR:-"${HOME}/.ssh"}"
                    echo "SSH CONFIG DIR: '${SSH_CONFIG_DIR}'"
                    git --version

                    git clone --depth=1 --branch "${CIRCLE_BRANCH}" --single-branch "${CIRCLE_REPOSITORY_URL}" .
                name: git shallow clone
executors:
    my-circleci-cli:
        docker:
            - image: ghcr.io/sunakan/evidence-suburi-2-tool:latest
jobs:
    validate-config:
        executor:
            name: my-circleci-cli
        resource_class: arm.medium
        steps:
            - git-shallow-clone
version: 2.1
workflows:
    validate-config:
        jobs:
            - validate-config

